### ISSUE TITLE
Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by mrmading** [ForestAdmin/lumber-forestadmin#1]
I use a database hosted in Mongo Atlas Cluster and I am trying to plug Forest Admin. 

When I run lumber the app generates successfully and I can see all models generated properly. However, when I run `lumber install lumber-forestadmin` I jump into the following error: 

`{ Error: getaddrinfo ENOTFOUND ***********.mongodb.net & *****-prod-qyfrc.mongodb.net:27017
   at errnoException (dns.js:50:10)
   at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
 name: ‘MongoNetworkError’,
 errorLabels: [ ‘TransientTransactionError’ ],
 [Symbol(mongoErrorContextSymbol)]: {} }`

It seems like the SRV string is not working when I try to run this command but it works well when generating Lumber app. Any suggestion?

**Comment by lucashdp** [comment]
I have the same problem !

**Comment by arnaudbesnier** [comment]
Hi @mrmading @lucashdp thank you for the feedback.
It should be fixed with `lumber-cli@2.2.2` and `lumber-forestadmin@1.1.0`.

Feel free to reopen the issue if that's not what you observe.
