### ISSUE TITLE
Self hosting?

### ISSUE THREAD

**Issue by ryanpcmcquen** [ForestAdmin/lumber-forestadmin#13]
Is it possible to self host Forest Admin?

**Comment by arnaudbesnier** [comment]
Hi @ryanpcmcquen,

The Admin Backend API generated by Lumber has to be hosted by yourself.
Would you like to host the interface too? If that's your question, we don't provide such feature.

Does it help?

If you want more information, feel free to join our community:
https://community.forestadmin.com

🌲🌲🌲
